[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]

[functions.scrape]
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core"]

[build.environment]
  # Disable secrets scanning for Firebase configuration
  # These are public client-side configuration values, not secret keys
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_FIREBASE_API_KEY,REACT_APP_FIREBASE_APP_ID,REACT_APP_FIREBASE_AUTH_DOMAIN,REACT_APP_FIREBASE_DATABASE_URL,REACT_APP_FIREBASE_MEASUREMENT_ID,REACT_APP_FIREBASE_MESSAGING_SENDER_ID,REACT_APP_FIREBASE_PROJECT_ID,REACT_APP_FIREBASE_STORAGE_BUCKET"
  # Chromium configuration for serverless functions
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200