services:
  - type: web
    name: orienteering-proxy
    runtime: node
    plan: free
    rootDir: proxy-server
    buildCommand: npm install
    startCommand: npm run start:simple
    envVars:
      - key: NODE_ENV
        value: production